# seguindo o exemplo do guiao 2 - instalar swap com ansible

---
- name: Install Mysql packages
  apt:
    name: "{{ item }}"
    state: latest
  loop: "{{ db_packages }}"

- name: Change MySQL bind-address
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address   = {{ app_db_ip }}'
    state: present
    backrefs: yes
  notify: restart mysql

- name: Create >Laravel.io database
  mysql_db: name={{ laravel_db_name }} state=present  # <---

- name: Cleanup users with same name accounts
  mysql_user:
    name: "{{ laravel_db_user }}"    # <---
    host_all: yes
    state: absent

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: "{{ laravel_db_user }}"
    password: "{{ laravel_db_password }}"
    priv: '*.*:ALL,GRANT'
    host: "{{ app_ip }}" # antes estava app_user_ip
    state: present


    